AllCops:
  TargetRubyVersion: 2.1
  Exclude:
  - 'db/**/*'
  - 'config/**/*'
  - 'ecript/**/*'
  - 'lib/rpc/grab_api/grab_api.rb'
Lint/Debugger:
  Enabled: true
Lint/DefEndAlignment:
  Enabled: true
Lint/DeprecatedClassMethods:
  Enabled: true
Lint/DuplicateMethods:
  Enabled: true
Lint/ParenthesesAsGroupedExpression:
  Enabled: true
Lint/RequireParentheses:
  Enabled: true
Lint/UnusedBlockArgument:
  Enabled: true
Lint/UnusedMethodArgument:
  Enabled: true
Lint/UnreachableCode:
  Enabled: true
Lint/UselessAccessModifier:
  Enabled: true
Lint/UselessAssignment:
  Enabled: true
Lint/UselessComparison:
  Enabled: true
Lint/UselessElseWithoutRescue:
  Enabled: true
Lint/UselessSetterCall:
  Enabled: true
Lint/Void:
  Enabled: true
Metrics/LineLength:
  Enabled: true
  Max: 120
Performance/Detect:
  Enabled: true
Performance/FlatMap:
  Enabled: true
Performance/ReverseEach:
  Enabled: true
Performance/Sample:
  Enabled: true
Performance/Size:
  Enabled: true
Style/AndOr:
  Enabled: true
  EnforcedStyle: conditionals
Style/BlockDelimiters:
  Enabled: true
Style/ClassAndModuleCamelCase:
  Enabled: true
Style/ClassCheck:
  Enabled: true
Style/ClassMethods:
  Enabled: true
Style/CollectionMethods:
  Enabled: true
Style/ConstantName:
  Enabled: true
Style/DefWithParentheses:
  Enabled: true
Style/DeprecatedHashMethods:
  Enabled: true
Style/EmptyLineBetweenDefs:
  Enabled: true
Style/FileName:
  Enabled: true
Style/For:
  Enabled: true
Style/HashSyntax:
  Enabled: true
Style/IndentationWidth:
  Enabled: true
Style/MethodCallParentheses:
  Enabled: true
Style/MethodDefParentheses:
  Enabled: true
Style/MethodName:
  Enabled: true
Style/MultilineTernaryOperator:
  Enabled: true
Style/NestedTernaryOperator:
  Enabled: true
Style/Not:
  Enabled: true
Style/ParallelAssignment:
  Enabled: true
Style/RedundantReturn:
  Enabled: true
Style/RedundantSelf:
  Enabled: true
Style/Semicolon:
  Enabled: true
Style/SignalException:
  Enabled: true
  EnforcedStyle: only_raise
Style/SpaceBeforeBlockBraces:
  Enabled: true
  EnforcedStyle: space
Style/SpaceBeforeFirstArg:
  Enabled: false
Style/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyle: space
Style/StringLiterals:
  Enabled: true
Style/UnlessElse:
  Enabled: true
Style/VariableName:
  Enabled: true
Style/WordArray:
  Enabled: true

# Explicitly disable checks that aren't part of our style guide
Style/AccessModifierIndentation:
  Enabled: false
Style/AccessorMethodName:
  Enabled: false
Style/Alias:
  Enabled: false
Style/AlignArray:
  Enabled: false
Style/AlignHash:
  Enabled: false
Style/AlignParameters:
  Enabled: false
Style/ArrayJoin:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/AsciiIdentifiers:
  Enabled: false
Style/Attr:
  Enabled: false
Style/BeginBlock:
  Enabled: false
Style/BarePercentLiterals:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/BlockEndNewline:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/CaseIndentation:
  Enabled: false
Style/CharacterLiteral:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/ClosingParenthesisIndentation:
  Enabled: false
Style/ColonMethodCall:
  Enabled: false
Style/CommandLiteral:
  Enabled: false
Style/CommentAnnotation:
  Enabled: false
Style/CommentIndentation:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DotPosition:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/ElseAlignment:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Style/EmptyLines:
  Enabled: false
Style/EmptyLinesAroundAccessModifier:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/EmptyLinesAroundMethodBody:
  Enabled: false
Style/EmptyLiteral:
  Enabled: false
Style/EndBlock:
  Enabled: false
Style/EndOfLine:
  Enabled: false
Style/EvenOdd:
  Enabled: false
Style/ExtraSpacing:
  Enabled: false
Style/InitialIndentation:
  Enabled: false
Style/FirstParameterIndentation:
  Enabled: false
Style/FlipFlop:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/IfWithSemicolon:
  Enabled: false
Style/IndentationConsistency:
  Enabled: false
Style/IndentArray:
  Enabled: false
Style/IndentHash:
  Enabled: false
Style/InfiniteLoop:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/LeadingCommentSpace:
  Enabled: false
Style/LineEndConcatenation:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/MultilineBlockLayout:
  Enabled: false
Style/MultilineIfThen:
  Enabled: false
Style/MultilineOperationIndentation:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/NegatedWhile:
  Enabled: false
Style/Next:
  Enabled: false
Style/NilComparison:
  Enabled: false
Style/NonNilCheck:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/OneLineConditional:
  Enabled: false
Style/OpMethod:
  Enabled: false
Style/OptionalArguments:
  Enabled: false
Style/ParenthesesAroundCondition:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/PercentQLiterals:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/PredicateName:
  Enabled: false
Style/Proc:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/RedundantException:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/RescueEnsureAlignment:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/SelfAssignment:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Style/SingleLineMethods:
  Enabled: false
Style/SpaceAfterColon:
  Enabled: false
Style/SpaceAfterComma:
  Enabled: false
Style/SpaceAfterControlKeyword:
  Enabled: false
Style/SpaceAfterMethodName:
  Enabled: false
Style/SpaceAfterNot:
  Enabled: false
Style/SpaceAfterSemicolon:
  Enabled: false
Style/SpaceBeforeComma:
  Enabled: false
Style/SpaceBeforeComment:
  Enabled: false
Style/SpaceBeforeSemicolon:
  Enabled: false
Style/SpaceAroundBlockParameters:
  Enabled: false
Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Style/SpaceAroundOperators:
  Enabled: false
Style/SpaceBeforeModifierKeyword:
  Enabled: false
Style/SpaceInsideBrackets:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  Enabled: false
Style/SpaceInsideParens:
  Enabled: false
Style/SpaceInsideRangeLiteral:
  Enabled: false
Style/SpaceInsideStringInterpolation:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/StructInheritance:
  Enabled: false
Style/SymbolLiteral:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/Tab:
  Enabled: false
Style/TrailingBlankLines:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInLiteral:
  Enabled: false
Style/TrailingWhitespace:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Style/UnneededCapitalW:
  Enabled: false
Style/UnneededPercentQ:
  Enabled: false
Style/TrailingUnderscoreVariable:
  Enabled: false
Style/VariableInterpolation:
  Enabled: false
Style/WhenThen:
  Enabled: false
Style/WhileUntilDo:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Lint/AmbiguousOperator:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
Lint/BlockAlignment:
  Enabled: false
Lint/CircularArgumentReference:
  Enabled: false
Lint/ConditionPosition:
  Enabled: false
Lint/EachWithObjectArgument:
  Enabled: false
Lint/ElseLayout:
  Enabled: false
Lint/EmptyEnsure:
  Enabled: false
Lint/EmptyInterpolation:
  Enabled: false
Lint/EndAlignment:
  Enabled: false
Lint/EndInMethod:
  Enabled: false
Lint/EnsureReturn:
  Enabled: false
Lint/Eval:
  Enabled: false
Lint/HandleExceptions:
  Enabled: false
Lint/InvalidCharacterLiteral:
  Enabled: false
Lint/LiteralInCondition:
  Enabled: false
Lint/LiteralInInterpolation:
  Enabled: false
Lint/Loop:
  Enabled: false
Lint/NestedMethodDefinition:
  Enabled: false
Lint/RescueException:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Lint/StringConversionInInterpolation:
  Enabled: false
Lint/UnderscorePrefixedVariableName:
  Enabled: false
Lint/UnneededDisable:
  Enabled: false
Performance/Count:
  Enabled: false
Performance/StringReplacement:
  Enabled: false
Rails/ActionFilter:
  Enabled: false
Rails/Date:
  Enabled: false
Rails/Delegate:
  Enabled: false
Rails/FindBy:
  Enabled: false
Rails/FindEach:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
Rails/Output:
  Enabled: false
Rails/ReadWriteAttribute:
  Enabled: false
Rails/ScopeArgs:
  Enabled: false
Rails/TimeZone:
  Enabled: false
Rails/Validation:
  Enabled: false
Style/Copyright:
  Enabled: false
Style/Encoding:
  Enabled: false
