activityId = undefined
$(document).ready ->

  redirectToTourPage = (activityId, lengthId) ->
    uri = '/tours?activity_id=' + activityId + '&length_id=' + lengthId
    window.location.href = uri
    return

  $('.activity-link').click (e) ->
    activityId = $(this).data('activity-id')
    return
  $('.length-link').click (e) ->
    lengthId = $(this).data('length-id')
    redirectToTourPage activityId, lengthId
    return
  return
# ---
# generated by coffee-script 1.9.2

# ---
# generated by js2coffee 2.2.0
